# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "883532b612cb6a6d291f60afaae94cc0"
application_url = "https://deserve-trembl-periodic-dimensional.trycloudflare.com"
embedded = true
name = "Demo-BillingApp"
handle = "demo-billingapp-1"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://deserve-trembl-periodic-dimensional.trycloudflare.com/auth/callback",
  "https://deserve-trembl-periodic-dimensional.trycloudflare.com/auth/shopify/callback",
  "https://deserve-trembl-periodic-dimensional.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "hungstore-vn.myshopify.com"
automatically_update_urls_on_dev = true
